name: adi_movie_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  carousel_slider: ^4.2.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  http: ^1.2.2

flutter:
  uses-material-design: true
